services:

  mailer:
    image: schickling/mailcatcher
    ports:
      - "1025:1025"
      - "1080:1080"
      
  database:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_USER: changeMe
      MYSQL_ROOT_PASSWORD: changeMe
      MYSQL_DATABASE: batabase_name
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8081:80'
    environment:
      PMA_HOST: database 
      
  php:
    container_name: php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/batabase_name
    depends_on:
      - database
  
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/batabase_name
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
      
  ngrok:
    container_name: ngrok
    image: wernight/ngrok
    ports:
    - "4040:4040"
    environment:
      NGROK_AUTHTOKEN: 2KmPPZyrylhQbYgGUl4VmUI1iVx_2ynmE13EobeiRjnGc9eWj # add token from https://dashboard.ngrok.com/get-started/setup
      command: sh -c 'ngrok http 8080' # forward the nginx service's port 8080
